# Generated by Django 5.2 on 2025-05-12 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cartriges', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата замены')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartriges.cartrige', verbose_name='расходник')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='devices.usableprinter', verbose_name='принтер')),
            ],
            options={
                'verbose_name': 'обслуживание',
                'verbose_name_plural': 'обслуживание',
                'db_table': 'operations',
            },
        ),
    ]
