# Generated by Django 5.2 on 2025-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('category', models.CharField(choices=[('cartrige', 'Картридж'), ('drum', 'Барабан')], max_length=8, verbose_name='Тип расходника')),
                ('printer', models.ManyToManyField(to='devices.printer', verbose_name='Совместимость')),
            ],
            options={
                'verbose_name': 'картридж',
                'verbose_name_plural': 'картриджи',
                'db_table': 'cartriges',
                'ordering': ('category', 'name'),
                'default_related_name': 'cartriges',
            },
        ),
    ]
