# Generated by Django 5.2 on 2025-05-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'принтер',
                'verbose_name_plural': 'принтеры',
                'db_table': 'printers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cartrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('category', models.CharField(choices=[('cartrige', 'Картридж'), ('drum', 'Барабан')], max_length=8, verbose_name='Тип расходника')),
                ('printer', models.ManyToManyField(to='cartriges.printer', verbose_name='Совместимость')),
            ],
            options={
                'verbose_name': 'картридж',
                'verbose_name_plural': 'картриджи',
                'db_table': 'cartriges',
                'ordering': ('category', 'name'),
                'default_related_name': 'cartriges',
            },
        ),
        migrations.CreateModel(
            name='UsablePrinter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.PositiveSmallIntegerField(unique=True, verbose_name='инвентаризационный номер')),
                ('serial_number', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='серийный номер')),
                ('status', models.CharField(choices=[('working', 'Исправен'), ('broken', 'Сломан')], max_length=8, verbose_name='Состояние')),
                ('comment', models.TextField(blank=True, max_length=256, null=True, verbose_name='комментарий')),
                ('ip_adress', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='IP адрес устройства')),
                ('host_name', models.CharField(blank=True, max_length=10, null=True, verbose_name='Имя хоста в сети')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildings.cabinet', verbose_name='кабинет')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartriges.printer', verbose_name='принтер')),
            ],
            options={
                'verbose_name': 'используемый принтер',
                'verbose_name_plural': 'используемые принтеры',
                'db_table': 'usable_printers',
                'ordering': ('cabinet__name',),
                'default_related_name': 'usable_printers',
            },
        ),
    ]
