# Generated by Django 5.2 on 2025-05-06 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'принтер',
                'verbose_name_plural': 'принтеры',
                'db_table': 'printers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Cartrige',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Модель')),
                ('slug', models.SlugField(max_length=256, unique=True, verbose_name='URL')),
                ('amount', models.PositiveSmallIntegerField(default=0, verbose_name='Количество')),
                ('category', models.CharField(choices=[('cartrige', 'Картридж'), ('drum', 'Барабан')], max_length=8, verbose_name='Тип расходника')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartriges.printer', verbose_name='Принтер')),
            ],
            options={
                'verbose_name': 'картридж',
                'verbose_name_plural': 'картриджи',
                'db_table': 'cartriges',
                'ordering': ('name',),
                'default_related_name': 'cartriges',
            },
        ),
    ]
