# Generated by Django 5.2 on 2025-05-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartriges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartrige',
            name='printer',
        ),
        migrations.AddField(
            model_name='cartrige',
            name='printer',
            field=models.ManyToManyField(to='cartriges.printer', verbose_name='Совместимость'),
        ),
    ]
