# Generated by Django 5.2 on 2025-05-06 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('cartriges', '0002_remove_cartrige_printer_cartrige_printer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartrige',
            options={'default_related_name': 'cartriges', 'ordering': ('category', 'name'), 'verbose_name': 'картридж', 'verbose_name_plural': 'картриджи'},
        ),
        migrations.CreateModel(
            name='UsablePrinters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_number', models.PositiveSmallIntegerField(max_length=16, unique=True, verbose_name='инвентаризационный номер')),
                ('status', models.CharField(choices=[('working', 'Исправен'), ('broken', 'Сломан')], max_length=8, verbose_name='Состояние')),
                ('comment', models.TextField(blank=True, max_length=256, null=True, verbose_name='комментарий')),
                ('cabinet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='buildings.cabinet', verbose_name='кабинет')),
                ('printer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cartriges.printer', verbose_name='принтер')),
            ],
            options={
                'verbose_name': 'используемый принтер',
                'verbose_name_plural': 'используемые принтеры',
                'db_table': 'usable_printers',
                'ordering': ('cabinet__name',),
                'default_related_name': 'usable_printers',
            },
        ),
    ]
